(function () {
  /*skycons 判斷*/
  var chooseSkycons = function (id, code) {
    if(code==="32" || code==="34" || code==="36"){
      skycons.set(id, "clear-day");
    } else if(code==="9" || code==="10" || code==="11" || code==="12" || code==="40") {
      skycons.set(id, "rain");
    } else if(code==="31" || code==="33"){
      skycons.set(id, "clear-night");
    } else if(code==="28" || code==="30"){
      skycons.set(id, "partly-cloudy-day");
    } else if(code==="27" || code==="29"){
      skycons.set(id, "partly-cloudy-night");
    } else if(code==="26") {
      skycons.set(id, "cloudy");
    } else if(code==="18") {
      skycons.set(id, "sleet");
    } else if(code==="14" || code==="15" || code==="16") {
      skycons.set(id, "snow");
    } else if(code==="23" || code==="24") {
      skycons.set(id, "wind");
    } else if(code==="19" || code==="20" || code==="21" || code==="22") {
      skycons.set(id, "fog");
    }
  }, GetWeather = function (city) {
    if(city==="連江縣 Lienchiang County"){
      city = "Lienchiang";
    }

    $.ajax('https://query.yahooapis.com/v1/public/yql', {
      method: 'GET',
      data: {
        q: 'select * from weather.forecast where woeid in (select woeid from geo.places(1) where text="' + city + '")',
        format: 'json'
      },
      success: function (data) {
        if (data.query.count === 0 || data.query.results.channel.item.title === 'City not found') {
          window.alert("Oops! The city's information can't be found.");
          return false;
        }

        console.log('data',data);
        var weatherInfo = data.query.results.channel,
        currentCondition = weatherInfo.item.condition.text,
        currentTemp = weatherInfo.item.condition.temp,
        currentCode = weatherInfo.item.condition.code,
        todayDate = weatherInfo.item.forecast[0].date,
        forecastInfo = [];

        forecastInfo[0] = weatherInfo.item.forecast[1];
        forecastInfo[1] = weatherInfo.item.forecast[2];
        forecastInfo[2] = weatherInfo.item.forecast[3];

        

        $('#currentTemp').text(FtoC(currentTemp));
        $('#todayDate').text(todayDate);
        $('#todayText').text(currentCondition);

        $('thead>tr>th:nth-child(1)').text(forecastInfo[0].date);
        $('#forecastTemp>th:nth-child(1)').text(FtoC(forecastInfo[0].low) +'-'+ FtoC(forecastInfo[0].high) + "℃");
        $('thead>tr>th:nth-child(2)').text(forecastInfo[1].date);
        $('#forecastTemp>th:nth-child(2)').text(FtoC(forecastInfo[1].low) +'-'+ FtoC(forecastInfo[1].high) + "℃");
        $('thead>tr>th:nth-child(3)').text(forecastInfo[2].date);
        $('#forecastTemp>th:nth-child(3)').text(FtoC(forecastInfo[2].low) +'-'+ FtoC(forecastInfo[2].high) + "℃");

        chooseSkycons("today", currentCode);
        chooseSkycons("day1", forecastInfo[0].code);
        chooseSkycons("day2", forecastInfo[1].code);
        chooseSkycons("day3", forecastInfo[2].code);
      }
    });
    return false;
  }, FtoC = function (t) {
    return Math.round(((t-32)*5)/9);
  };

  /*
Skycons is a set of ten animated weather glyphs, procedurally generated by JavaScript using the HTML5 canvas tag.
http://darkskyapp.github.io/skycons/
*/
  var skycons = new Skycons();
  // on Android, a nasty hack is needed: {"resizeClear": true}

  // you can add a canvas by it's ID...
  // skycons.add("today", Skycons.PARTLY_CLOUDY_DAY);
  // skycons.add("day1", Skycons.CLEAR_DAY);
  // skycons.add("day2", Skycons.CLOUDY);
  // skycons.add("day3", "wind");

  // start animation!
  skycons.play();
  
  // want to change the icon? no problem:
  // skycons.set("today", Skycons.PARTLY_CLOUDY_NIGHT);
  
/*
Get value from Bootstrap dropdown menu
*/

  GetWeather("taipei");

  $(document).ready(function () {
    $('#dropdown li').on('click', function(){
      alert($(this).text());
      $('#dropCurrent').text($(this).text());
      GetWeather($(this).text());
    });
  });
}());